### ISSUE TITLE
Upgrade to latest InvenioRDM

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#108]
### Stats
The issue here is that the new invenio-stats has 2 breaking changes:
1. a new field `updated_timestamp` in the template
2. the creation of events indices has been changed from daily to monthly

**Upgrade**
1. Change config of CDS to use yearly index instead, it should be more than enough. Example PR: https://github.com/inveniosoftware/invenio-stats/pull/143
2. Put the site down, workers included. Deploy.
3. Using OpenSearch Dashboard, update templates 
```
GET /_cat/templates to get all templates
for each template in:
    1. Copy the body of each template, without the first line "<PREFIX>-record-view-v1.0.0" with the index name:
  
        GET /_template/<PREFIX>-record-view-v1.0.0
        GET /_template/<PREFIX>-file-download-v1.0.0   
        GET /_template/<PREFIX>-aggr-record-view-v1.0.0
        GET /_template/<PREFIX>-aggr-file-download-v1.0.0

    2. add the new field to the body of record-view and aggr-record-view:

            "updated_timestamp": {
                "type": "date"
            }


    2.1 add the new field to the body of file-download and aggr-file-download:
            "volume": {
                "type": "double"
            },

            "updated_timestamp": {
                "type": "date"
            }

    3. Replace the template

        PUT /_template/<PREFIX>-aggr-record-view-v1.0.0
        {
             new body
        }
```
4. Update mappings to add the new field (do not touch `<PREFIX>-stats-bookmarks` index)
```
PUT /<PREFIX>-events-*,<PREFIX>-stats-file*,<PREFIX>-stats-record* /_mapping
{
  "properties": {
    "updated_timestamp": {
      "type": "date"
    }
  }
}
```

5. Migrate/Reindex daily indices to the current year one. We should end up having a 2 events stats (views/downloads) and 2 stats (views/downloads) indices.
```bash
# adjust months/days as needed
URL="https://<insert url with prefix>"
USER="<insert user>"
PSW="<insert psw>"
INDEX_PREFIX="<insert prefix>"

for index in record-view file-download; do
for month in {07..10}; do
_month=$(printf "%02d" $month)
for day in {01..31}; do
_day=$(printf "%02d" $day)
curl -u ${USER}:${PSW} -XPOST "${URL}/_reindex" -H 'Content-Type: application/json' -d'
{
  "source": {"index": "'${INDEX_PREFIX}'-events-stats-'${index}'-2023-'${_month}'-'${_day}'"},
  "dest": {"index": "'${INDEX_PREFIX}'-events-stats-'${index}'-2023-'${_month}'"}
}'
done
done
done
```

6. After `refresh` time passed, validate the count:
```
# month should be equal or highet than all days
GET /zenodo-dev-events-stats-record-view-2023-10/_count 
GET /zenodo-dev-events-stats-record-view-2023-10-*/_count
```

7. When all ok, delete the previous daily `-events-stats-` indices.
```bash
URL="https://<insert url with prefix>"
USER="<insert user>"
PSW="<insert psw>"
INDEX_PREFIX="<insert prefix>"

for index in record-view file-download; do
for month in {07..10}; do
_month=$(printf "%02d" $month)
for day in {01..31}; do
_day=$(printf "%02d" $day)
echo "Deleting ${URL}/${INDEX_PREFIX}-events-stats-${index}-2023-${_month}-${_day}"
curl -u ${USER}:${PSW} -XDELETE "${URL}/${INDEX_PREFIX}-events-stats-${index}-2023-${_month}-${_day}"
done
done
done
```

### Notifications
https://github.com/inveniosoftware/invenio-rdm-records/commit/13d70c911509dba9f762ee90cf5d5e98985e70f8
`invenio-rdm-records` v4.29

**Comment by zzacharo** [comment]
- Cleanup indices
```bash
# (stats are kept) on index destroy
$ invenio index destroy --yes-i-know
$ invenio index queue init purge
```
- Run the [upgrade script](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py)
- Recreate indices
```bash
$ invenio index init --force
``` 
- Rebuild all indices (stats are kept)
```bash
invenio rdm rebuild-all-indices
```

**Comment by psaiz** [comment]
What about changing the script to detect the daily indices?
I mean, instead of 
```
for index in record-view file-download; do
for month in {07..10}; do
_month=$(printf "%02d" $month)
for day in {01..31}; do
_day=$(printf "%02d" $day)
```
something like

```

**Comment by ntarocco** [comment]
Remove the details.html [template](https://github.com/CERNDocumentServer/cds-rdm/blob/master/templates/semantic-ui/invenio_app_rdm/records/detail.html) once upgraded.

**Comment by zzacharo** [comment]
# Local services setup changes

- vocabularies affiliations change: https://github.com/inveniosoftware/invenio-rdm-records/commit/e3df51f5a9f25c20a4234e0d6e524c8d021d8fd2
Schemes is removed is removed from affiliations
```
affiliations:
  pid-type: aff
  data-file: vocabularies/affiliations_ror.yaml
```

# Documentation

- New access request for allowing users to request access to restricted records. Controlled by record managers in the record i.e allow or not people to request access.
- Share access with individual people in the record level
- Manage communities: set branding action

# Data migration

- psql $DB_URI -c "DELETE FROM alembic_version WHERE version_num = 'cfcb8cb78708';"
- invenio alembic upgrade

# recreate indices
- invenio index destroy --yes-i-know
- invenio index init
- invenio rdm rebuild-all-indices

# Upgrade stats

## Backup stats

### Export them to json locally

NODE_TLS_REJECT_UNAUTHORIZED=0 && elasticdump \
  --input="https://{user}:{psw}@{host}:{port}/os" \
  --input-index='{prefix}-events-stats-*' \
  --output='./events-stats.json'

### Import them from backup

elasticdump \
  --input=./events-stats.json \
  --output='http://localhost:9200'


## UpdGEate bookmarks to a day before the upgrade

POST /cds-rdm-stats-bookmarks/_doc
{
         "date": "2024-01-22T10:10:00.102810",
          "aggregation_type": "file-download-agg"
}
POST /cds-rdm-stats-bookmarks/_doc
{
         "date": "2024-01-22T10:10:00.102810",
          "aggregation_type": "record-view-agg"
}
POST /cds-rdm-stats-bookmarks/_doc
{
         "date": "2024-01-22T10:10:00.102810",
          "aggregation_type": "stats_reindex"
}

## Reindex daily indices to current month one

```bash
URL="http://localhost:9200"
USER="admin"
PSW="admin"
INDEX_PREFIX="cds-rdm"

for index in record-view file-download; do
  for year in {2023..2024}; do
    for month in {07..12}; do
      _month=$(printf "%02d" $month)
      days_in_month=$(cal $month $year | awk 'NF {DAYS = $NF}; END {print DAYS}')
      for day in $(seq -w 1 $days_in_month); do
        _day=$(printf "%02d" $day)
        curl -u ${USER}:${PSW} -XPOST "${URL}/_reindex" -H 'Content-Type: application/json' -d'
        {
          "source": {"index": "'${INDEX_PREFIX}'-events-stats-'${index}'-'${year}'-'${_month}'-'${_day}'"},
          "dest": {"index": "'${INDEX_PREFIX}'-events-stats-'${index}'-'${year}'-'${_month}'"}
        }'
      done
    done
  done
done
```

## Count docs

GET /cds-rdm-events-stats-record-view-2024-03/_count
GET /cds-rdm-events-stats-record-view-2024-03-*/_count


GET /cds-rdm-events-stats-file-download-2024-03/_count
GET /cds-rdm-events-stats-file-download-2024-03-*/_count

**Comment by zzacharo** [comment]
All changes applied to production.
