### ISSUE TITLE
Dojson rules for SSPN metadata

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#128]
* The old recid should redirect to the new cool ID. One possible solution is to mint both, and the old recid simply redirects to the new one.
* The migration should also include deleted records.
* All the revisions should be added as a blob in the migrated record.

- [x] mint legacy recid
- [x] check for duplicated records
- [ ] ingest for community
- [x] add dry run mode with service validate only
- [ ] create token and modify the script to use the token when copying the files dump
- [ ] add previous revisions blob (to discuss how)
- [ ] enable DOI on dev
- [ ] bibdocid do we need it migrated? could be useful for stats

### Open questions
- Report number: we are planning to store it in `alternative identifiers`, and the scheme name should be decided. Possible names could be `CDS report number`, `CDS number`. We would like to avoid having it as a more prominent field, for example as a custom field. This should also be discussed with the Library.

## source of truth for mappings
https://docs.google.com/spreadsheets/d/1OHMDiMfBD1Aam-kteIuBL9tEPK-C-Jevw-NcmGGxRvY/edit?gid=1124757768#gid=1124757768

**Comment by kpsherva** [comment]
To be discussed:
-----------------

1. how to migrate creation date (idea: custom service for migration only)
2. how to solve problem of access https://github.com/CERNDocumentServer/cds-migrator-kit/blob/master/cds_migrator_kit/rdm/migration/load.py#L53 (custom service for migration only could help with preparing the access too)
3. how we create revisions
4. resources for the migration pod (locally the migration was faster, on dev is 2.5k in 30+ minutes) -  Alex is suggesting bulk index after the ingestion, not during (also points to custom service)
5. DOI - how to go with no DOIs, do we go with (to be tested):

```
RDM_PERSISTENT_IDENTIFIERS = {
    # DOI automatically removed if DATACITE_ENABLED is False.
    "doi": {
        "providers": ["datacite", "external"],
        "required": False,
        "label": _("DOI"),
        "validator": idutils.is_doi,
        "normalizer": idutils.normalize_doi,
        "is_enabled": providers.DataCitePIDProvider.is_enabled,
    },
    "oai": {
        "providers": ["oai"],
        "required": True,
        "label": _("OAI"),
        "is_enabled": providers.OAIPIDProvider.is_enabled,
    },
}
```
