### ISSUE TITLE
Files migration for SSPN

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#129]
Script to import done in the past:

https://github.com/CERNDocumentServer/cds-ils/blob/master/cds_ils/migrator/eitems/api.py#L111

JSON is coming from the `invenio migrator dump` (the tool installed already in legacy)

in the past we have mounted EOS on one of the webnodes and copied the whole file structure under temporary folder and imported it by the script above to ILS

The old URL path should still work and directly link to the file and versions should redirect correctly to the new one.
Double-check all possible URLs path/routes. It looks like that [there is some code done here](https://gitlab.cern.ch/cds-team/cds-legacy/blob/master/src/wn-cdsweb/lib/python/invenio/bibdocfile_webinterface.py#L184), but it might not take into account URL params (and we should).

When migrating, versions of the file should be kept.

**Comment by kpsherva** [comment]
moved the files redirection part to a separate issue
