### ISSUE TITLE
Bootstrap migration

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#142]
- Decide how to organize/structure the code
  - use rdm-migrator?
  - use service layers when importing?
  - resume migrator kit/UI

### Done when
We are able to:
1. export from CDS
2. review transformation via UI
3. import in the new CDS

This excludes any transformation rule: having title and a fake creator is enough

**Comment by kpsherva** [comment]
![Image](https://github.com/CERNDocumentServer/cds-rdm/assets/38131488/88afc18d-702f-4c2d-baee-650b25886971)
