### ISSUE TITLE
set a default CERN license when missing and on new uploads

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-rdm#178]
![Screenshot 2024-08-28 at 09 54 46](https://github.com/user-attachments/assets/d4b8c100-aeda-49cc-87f1-828c00f24c66)

**Comment by ntarocco** [comment]
@sakshamarora1 here the task is to verify that, by default, CC-BY is selected in the form

**Comment by sakshamarora1** [comment]
Yes, CC-BY is selected by default in both `invenio-app-rdm` and `cds-rdm`.
https://github.com/CERNDocumentServer/cds-rdm/blob/ad756e5ca0d1d5f6c1019b829868832a2446078f/invenio.cfg#L148-L162
