### ISSUE TITLE
communities carousel: review presence of New upload button

### ISSUE THREAD

**Issue by anikachurilova** [CERNDocumentServer/cds-rdm#185]
TBD: shall "New upload" button be removed from the featured communities carousel?
The button was removed in Zenodo because of communities complaining that they get a lot of spam review requests as it's easily accessible from the frontpage

<img width="1231" alt="Screenshot 2024-08-09 at 17 49 06" src="https://github.com/user-attachments/assets/9539dcdd-4285-4bda-9733-8ecf8c219f32">

**Comment by ntarocco** [comment]
We probably won't have any carousel, closing for the time being.
