### ISSUE TITLE
Names vocab: Evaluate generate an hash from the person id, generated with a secret, and use it as name id.

### ISSUE THREAD

**Issue by jrcastro2** [CERNDocumentServer/cds-rdm#192]
The person id cannot be exposed and therefore we might want to generate an hash from the person id, generated with a secret, and use it as name id.

This level of protection should match the one enforced by the CERN Phonebook. We might want to contact them and ask this.

**Comment by ntarocco** [comment]
After discussions, if we cannot expose the Person ID, there is no need to create a hash. We can maybe expose an ID.
