### ISSUE TITLE
community auto-submit: remove notification about request auto-acceptance

### ISSUE THREAD

**Issue by anikachurilova** [CERNDocumentServer/cds-rdm#203]
If the community's `review_policy` is set to `open` or `members`, then users are able to submit a record to a community, bypassing the review process. In this case, the review request is still created and auto-accepted by System. 

The problem: request acceptance notification is sent to the request creator, and as this accept action is made by system user, we are getting an exception. This notification is probably not needed at all, because as user is submitting the record directly, they don't even need to know that there was a request created. 

Sentry exception: https://cds-sentry.web.cern.ch/sentry/cds-rdm/issues/34056/events/816855/

**Comment by ntarocco** [comment]
We discussed quickly in IRL, can we solve this differently? We might want to have in the future that the system will send automatic e-mails, it might make sense.

By the way it looks like that we cannot access the exception?

So I would split the fix in 2 parts:
1. make system identity that can send notifications: this might mean fixing some notifications/builders logic (depending on the issue)
2. exclude sending notifications on auto-accept. For this part, we could do the following:
    1. inject a param in the auto-accept [execute_action](https://github.com/inveniosoftware/invenio-rdm-records/blame/master/invenio_rdm_records/services/community_inclusion/service.py#L66)
    2. allow `kwargs` [here](https://github.com/inveniosoftware/invenio-requests/blame/master/invenio_requests/services/requests/service.py#L227)
    3. implement the condition [here](https://github.com/inveniosoftware/invenio-rdm-records/blame/master/invenio_rdm_records/requests/community_submission.py#L84-L85) based on this param

    Another way would be to create a new action, very similar to `Accept` (e.g. `AutoAccept`), and avoid the notification. However, I am not sure how hard it is that, and if it is actually better...
