### ISSUE TITLE
rdm(sspn): improve affliations search

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-rdm#228]
- [x] to start: copy all the migration artifacts to your local (we are planning to do the full migration) the instruction on how to do that is available in the readme in `rdm` subfolder.
- [x] fix local tests (some fields were not taken into account (**Not part of the affiliations task**)
- [x] find a better way to match (search for) the affiliations - in many cases you will see the search fails even if the affiliation is present in the vocabulary

**Comment by zzacharo** [comment]
completed by https://github.com/CERNDocumentServer/cds-migrator-kit/commit/cfbbcd417f20ba1620bfe29eb1d4bf2f6d273e7a
