### ISSUE TITLE
create sharing for restricted files record (decide if as migration steam or separately)

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-rdm#232]
For all the migrated records of Summer student notes community which have the restricted files, add CERN employees to read access via group "access grants"

1. identify all the records in summer student notes community which have restricted files
2. grant access to these records to cern-personnel group.

**Comment by sakshamarora1** [comment]
Completed!
<img width="1725" alt="Screenshot 2024-12-19 at 16 48 01" src="https://github.com/user-attachments/assets/37720e2e-9bd7-4459-bb19-23d163df1084" />
