### ISSUE TITLE
DOI: optional/on-demand in CDS

### ISSUE THREAD

**Issue by zzacharo** [CERNDocumentServer/cds-rdm#246]
We are evaluating to change the DOI feature and make it optional/on-demand in CDS.

**Comment by PaulinaBaranowska** [comment]
For the Summer Students, we believe all records should be assigned a DOI as it's unlikely that they receive a DOI from another source.
In general, I think all records should by default offer the option to mint a DOI but it should be clear in the submission form what the options are of why you are opting out of creating a DOI (e.g. I already have a DOI through arXiv, I submitted this paper to a journal etc.). There should not be an option "I do not want a DOI". This would then align with the new OC6 revision as every CERN document should have a PID (if the new CDS will not have report numbers anymore).
I guess it's best to discuss this in person.

**Comment by michamos** [comment]
still incorrect automation @zzacharo
