### ISSUE TITLE
Field `595__z:UNCL`

### ISSUE THREAD

**Issue by zzacharo** [CERNDocumentServer/cds-rdm#248]
- [Example](https://cds.cern.ch/record/1596235/export/hm): refers to [https://cds.cern.ch/collection/ATS UNCLASSIFIED](https://cds.cern.ch/collection/ATS%20UNCLASSIFIED) 
- This value is there because the Summer Student submission form is a [Departmental Notes submission](https://cds.cern.ch/submit?ln=en&doctype=DEPIN), so also used by ATS. 
- Feels like an error in CDS so can it be dropped?

**Comment by PaulinaBaranowska** [comment]
For SSPN this can be ignored, but we need to understand better what this means for other collections.

**Comment by ntarocco** [comment]
Thank you @PaulinaBaranowska. Completed
