### ISSUE TITLE
Minor improvements around LDAP fetching

### ISSUE THREAD

**Issue by jrcastro2** [CERNDocumentServer/cds-rdm#77]
Address the following comments:
- [ ] Consider adding `Affiliations` from ldap information, here the comment: https://github.com/CERNDocumentServer/cds-rdm/pull/75#discussion_r1234199446
- [ ] Do we want to expose the email (and allow users to search for it) here comment: https://github.com/CERNDocumentServer/cds-rdm/pull/75#discussion_r1233732172
- [ ] Ldap api, update the indexing of users to be done with batches: https://github.com/CERNDocumentServer/cds-rdm/pull/75#discussion_r1234147161
- [ ] Improve loading of config: https://github.com/CERNDocumentServer/cds-rdm/pull/66#discussion_r1234896027
- [x] Does it make sense to populate the username with data from LDAP, if yes, then we should probably disable this field, to avoid users to update it
- [ ] Have a look to this Sentry exception: https://cds-sentry.web.cern.ch/sentry/cds-rdm/issues/32400

**Comment by ntarocco** [comment]
Superseeded by https://github.com/CERNDocumentServer/cds-rdm/issues/196
