### ISSUE TITLE
missing redirection to record after login

### ISSUE THREAD

**Issue by ppanero** [CERNDocumentServer/cds-rdm#78]
1- Got a link for a record (https://sandbox-cds-rdm.web.cern.ch/records/7hqpp-y1r77)
2- I was not logged in (never, this was the first time).
3- Login with CERN SSO
4- Redirection took me to linked accounts
    expected: take me to the record

**Comment by kpsherva** [comment]
to fix in https://github.com/inveniosoftware/invenio-oauthclient/blame/3cf5ec52a81e6edb17b43349bc8eb4fdeb514160/invenio_oauthclient/views/client.py#L89
