### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-rdm#80]
<img width="1683" alt="Screenshot_2023-06-20_at_16 42 38" src="https://github.com/CERNDocumentServer/cds-rdm/assets/38131488/c7aa6ccc-ad01-47a6-b4d5-127457604380">
<img width="1461" alt="Screenshot_2023-06-21_at_10 43 03_1" src="https://github.com/CERNDocumentServer/cds-rdm/assets/38131488/4b21065b-5b51-468b-ac87-785059ece948">
<img width="453" alt="Screenshot 2023-06-23 at 11 36 56" src="https://github.com/CERNDocumentServer/cds-rdm/assets/38131488/64ce7885-6abb-4ffb-8d91-2dba42e96f44">

Issues with resolution changes:

![Image](https://github.com/CERNDocumentServer/cds-rdm/assets/38131488/45d637d7-32ab-49d5-a120-9d85140c2d84)
![Image](https://github.com/CERNDocumentServer/cds-rdm/assets/38131488/3aa938b9-c274-46e8-94b7-d87859849c7e)

**Comment by jrcastro2** [comment]
Another small issue 
![Screenshot from 2023-06-30 13-25-45](https://github.com/CERNDocumentServer/cds-rdm/assets/15194802/eecb115a-c980-4380-9fa0-a0336f64f1a6)

**Comment by zzacharo** [comment]
After latest upgrade, still the responsiveness related issues are there.

**Comment by ntarocco** [comment]
Other issue with responsive design: https://new-cds.cern.ch/records/c2948-e8875

![WhatsApp Image 2024-04-16 at 20 03 25](https://github.com/CERNDocumentServer/cds-rdm/assets/2089455/91bf8725-812f-4f91-b346-315fc8710bde)

**Comment by ntarocco** [comment]
In the responsive website, we are also missing a minium left/right padding.

**Comment by ntarocco** [comment]
The banner is covering the close button of the menu when opened in the responsive version.
<img width="1106" alt="Screenshot 2024-05-31 at 11 25 06" src="https://github.com/CERNDocumentServer/cds-rdm/assets/2089455/31671e65-1d2e-4aa6-b845-d755f1a1ed81">

**Comment by anikachurilova** [comment]
Another spacing issue: 
<img width="855" alt="Screenshot 2024-06-24 at 11 08 42" src="https://github.com/CERNDocumentServer/cds-rdm/assets/61321254/a8551749-e992-4dc9-bf2a-95075ff2810a">

**Comment by anikachurilova** [comment]
What an error page looks like:
<img width="1507" alt="Screenshot 2024-06-26 at 13 47 50" src="https://github.com/CERNDocumentServer/cds-rdm/assets/61321254/9e1409b6-c698-4485-9ee2-4e4f66918610">
