### ISSUE TITLE
LDAP sync improvements

### ISSUE THREAD

**Issue by jrcastro2** [CERNDocumentServer/cds-rdm#86]
None of the reviewers (me and David) have worked with LDAP so our knowledge there is limited. Might need another review.

We did not have time to go through `api.py`, `client.py` and `user_importer.py`, those still need reviewing.

_Originally posted by @ppanero in https://github.com/CERNDocumentServer/cds-rdm/pull/75#pullrequestreview-1490677656_

**Comment by ntarocco** [comment]
We will rework this in the future. Closing for now.
