### ISSUE TITLE
Require a community when uploading

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#88]
In the first phase of CDS-RDM, we should ensure that users must select an existing communities when submitting.

Related tasks:

- [ ] https://github.com/inveniosoftware/product-rdm/issues/183

**Comment by Samk13** [comment]
@ntarocco [1813](https://github.com/inveniosoftware/invenio-rdm-records/pull/1813) hasn't been merged yet. Should it be reopened?

**Comment by ntarocco** [comment]
@Samk13 we will not probably enable this in our institutional repo. We decided to close [this](https://github.com/inveniosoftware/product-rdm/issues/183) instead, when completed.
